/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'skyid' at '15/12/15 15:06' with Gradle 2.9
 *
 * @author skyid, @date 15/12/15 15:06
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
